curpud/courses/models.py
import peewee as orm
from flask_admin.contrib.peewee import ModelView
from flask import url_for, redirect
import flask_login

from curpud import db
from curpud.auth.models import User


# Translations
place_label = 'Lugar'
name_label = 'Nombre'
type_label = 'Tipo'
proofs_file_label = 'Pruebas'
assistent_label = 'Asistente'
init_date_label = 'Fecha de Inicio'
end_date_label = 'Fecha de Fin'


class BaseModel(orm.Model):
    class Meta:
        database = db


class BaseModelView(ModelView):
    can_export = True
    details_modal = True

    def is_accessible(self):
        auser = flask_login.current_user
        if auser.is_anonymous:
            return False
        user = User.get(User.login == auser.id)
        return auser.is_authenticated and user.is_admin

    def inaccessible_callback(self, name, **kwargs):
        # redirect to login page if user doesn't have access
        return redirect(url_for('auth.login'))


class TypeCourse(BaseModel):
    name = orm.CharField(
        unique=True
    )

    def __str__(self):
        return self.name


class TypeCourseView(BaseModelView):
    column_labels = {
        'name': name_label
    }

    form_args = {
        'name': {
            'label': name_label
        }
    }

    column_searchable_list = ['name']


class Course(BaseModel):
    name = orm.CharField(
        unique=True
    )
    assistent = orm.CharField()
    place = orm.TextField()
    type = orm.ForeignKeyField(
        TypeCourse,
        related_name='courses'
    )
    init_date = orm.DateField()
    end_date = orm.DateField()
    proofs_file = orm.CharField(unique=True)

    def __str__(self):
        return "{} {}".format(self.name, self.place)


class CourseView(BaseModelView):
    column_labels = {
        'name': name_label,
        'assistent': assistent_label,
        'place': place_label,
        'type': type_label,
        'init_date': init_date_label,
        'end_date': end_date_label,
        'proofs_file': proofs_file_label
    }

    form_args = {
        'name': {
            'label': name_label
        },
        'assistent': {
            'label': assistent_label
        },
        'place': {
            'label': place_label
        },
        'type': {
            'label': type_label
        },
        'init_date': {
            'label': init_date_label
        },
        'end_date': {
            'label': end_date_label
        },
        'proofs_file': {
            'label': proofs_file_label
        }
    }

    column_searchable_list = ['name', 'assistent', 'place', TypeCourse.name]

curpud/courses/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired
from wtforms import StringField, SelectField, DateField
from wtforms.validators import DataRequired

from .models import TypeCourse


class AddCourseForm(FlaskForm):
    name = StringField('Tema', validators=[
        DataRequired()
    ])
    place = StringField('Lugar', validators=[
        DataRequired()
    ])
    type = SelectField(
        'Tipo',
        validators=[
            DataRequired(message="Tipo faltante")
        ],
        coerce=int
    )
    init_date = DateField('Fecha de Inicio', validators=[
        DataRequired()
    ])
    end_date = DateField('Fecha de Fin', validators=[
        DataRequired()
    ])

    proofs = FileField('Pruebas')

    def __init__(self):
        FlaskForm.__init__(self)
        self.type.choices = [
            (t.id, t.name)
            for t in TypeCourse.select().order_by(
                TypeCourse.name
            )
        ]

curpud/publications/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired
from wtforms import StringField
from wtforms.validators import DataRequired


class AddPublicationForm(FlaskForm):
    issn = StringField('ISSN de la Revista', validators=[
        DataRequired()
    ])
    doi = StringField('DOI de la Publicación', validators=[
        DataRequired()
    ])
    proofs = FileField('Pruebas')

curpud/__init__.py
from hashlib import md5
from flask import (
    Flask,
    render_template,
    redirect,
    url_for,
    abort,
    jsonify,
    g
)
import flask_login
import flask_admin
import peewee as orm


# App global configuration
app = Flask(__name__)
app.config.from_object('config.DevelopmentConfig')


# jinja template configuration
app.jinja_env.trim_blocks = True
app.jinja_env.lstrip_blocks = True


# Database global configuration
db = orm.MySQLDatabase(
    'curpud',
    host=app.config['DB_HOST'],
    user=app.config['DB_USER'],
    passwd=app.config['DB_PASSWD']
)

from .publications.models import (
    Relevance, RelevanceView,
    DataBase, DataBaseView,
    Journal, JournalView,
    Publication, PublicationView
)
from .courses.models import (
    TypeCourse, TypeCourseView,
    Course, CourseView
)
from .auth.models import User, AuthUser

try:
    db.connect()
    db.create_tables([User])
    db.create_tables([Relevance, DataBase, Journal])
    db.create_tables([Publication])
    db.create_tables([TypeCourse, Course])
except Exception as e:
    pass


# Admin panel configurations
admin = flask_admin.Admin(
    app, name='curpud',
    base_template='custom_admin/master.html',
    template_mode='bootstrap3'
)
admin.add_views(
    RelevanceView(Relevance, 'Categorías'),
    DataBaseView(DataBase, 'Bases de Datos'),
    JournalView(Journal, 'Revistas'),
    PublicationView(Publication, 'Publicaciones'),
    TypeCourseView(TypeCourse, 'Tipos de Cursos'),
    CourseView(Course, 'Cursos')
)


# Authentication configuration
login_manager = flask_login.LoginManager()
login_manager.init_app(app)


@login_manager.user_loader
def user_loader(login):
    try:
        user = User.get(User.login == login)
        auser = AuthUser()
        auser.id = user.login
        return auser
    except:
        return


@login_manager.request_loader
def request_loader(request):
    login = request.form.get('login')
    try:
        user = User.get(User.login == login)
        auser = AuthUser()
        auser.id = user.login

        passwd = md5(request.form['pw'].encode()).hexdigest()
        auser.is_authenticated = passwd == user.passwd
        return auser
    except:
        return


@login_manager.unauthorized_handler
def unauthorized_handler():
    abort(404)


@app.before_request
def before_request():
    g.db = db
    g.db.connect()


@app.after_request
def after_request(response):
    g.db.close()
    return response


@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404


# Custom errors
class CurpudError(Exception):
    def __init__(self, msg):
        Exception.__init__(self, msg)
        self.msg = msg

    def to_dict(self):
        return {
            'description': self.msg,
            'status': 'error'
        }


@app.errorhandler(CurpudError)
def fbcm_error_handler(error):
    response = jsonify(error.to_dict())
    return response


@app.route('/')
def index():
    return redirect(url_for('publications.index'))


@app.route('/api/publicaciones/<user>/')
def api_list(user):
    json = {}
    try:
        json = {
            'status': 'ok',
            'profesor': user,
            'publicaciones': [
                p.to_dict()
                for p in Publication.select().where(
                    Publication.owner == user
                )
            ]
        }
    except:
        json = {
            'status': 'error'
        }
    finally:
        return jsonify(json)


@app.route('/api/publicaciones/<user>/<relevance>/')
def api_list_relevance(user, relevance):
    try:
        json = {
            'status': 'ok',
            'profesor': user,
            'publicaciones': [
                p.to_dict()
                for p in Publication.select().where(
                    Publication.journal.database.relevance.name == relevance &
                    Publication.owner == user
                )
            ]
        }
    except:
        json = {
            'status': 'error'
        }
    finally:
        return jsonify(json)


from .auth.views import auth
from .courses.views import cour
from .publications.views import pub

app.register_blueprint(auth)
app.register_blueprint(cour)
app.register_blueprint(pub)

curpud/courses/views.py
import os

from werkzeug.utils import secure_filename
import flask_login
from flask import (
    Blueprint,
    redirect,
    url_for,
    abort,
    request,
    render_template,
    send_from_directory
)

from curpud import CurpudError
from curpud import app
from curpud.tools import get_first_error
from .forms import AddCourseForm
from .models import Course, TypeCourse


cour = Blueprint('courses', __name__, url_prefix='/cursos')


@cour.route('/')
def index():
    form = AddCourseForm()
    courses = Course.select()
    return render_template(
        'courses/list.html',
        courses=courses,
        form=form
    )


@cour.route('/profesor/<user>/')
def list(user):
    form = AddCourseForm()
    courses = Course.select().where(Course.assistent == user)
    return render_template(
        'courses/list.html',
        courses=courses,
        form=form
    )


@cour.route('/id/<id>/')
def view(id):
    try:
        course = Course.get(Course.id == id)
    except:
        abort(404)
    else:
        return render_template(
            'courses/view.html',
            course=course
        )


@cour.route('/add/', methods=['POST'])
@flask_login.login_required
def add():
    user = flask_login.current_user
    form = AddCourseForm()
    if form.validate_on_submit():
        f = form.proofs.data
        filename = secure_filename(user.id + f.filename)
        f.save(os.path.join(
            app.instance_path, 'files', 'courses', filename
        ))

        Course.create(
            assistent=user.id,
            name=form.name.data,
            place=form.place.data,
            type=TypeCourse.get(form.type.data == TypeCourse.id),
            init_date=form.init_date.data,
            end_date=form.end_date.data,
            proofs_file=filename
        )
        return redirect(url_for('courses.list', user=user.id))
    else:
        raise CurpudError(get_first_error(form))


@cour.route('/delete/', methods=['POST'])
@flask_login.login_required
def delete():
    raise CurpudError("Acción no implementada!")
    user = flask_login.current_user
    return redirect(url_for('courses.list', user=user.id))


@cour.route('/file/<id>')
def serve_file(id):
    try:
        course = Course.get(Course.id == id)
    except:
        abort(404)
    else:
        return send_from_directory(
            os.path.join(app.instance_path, 'files', 'courses'),
            course.proofs_file
        )

curpud/publications/views.py
import os

from werkzeug.utils import secure_filename
import flask_login
from flask import (
    Blueprint,
    redirect,
    url_for,
    abort,
    request,
    render_template,
    send_from_directory
)

from curpud import CurpudError
from curpud import app
from .forms import AddPublicationForm
from curpud.tools import get_first_error
from .models import Journal, Publication


pub = Blueprint('publications', __name__, url_prefix='/publicaciones')


@pub.route('/')
def index():
    form = AddPublicationForm()
    publications = Publication.select()
    return render_template(
        'publications/list.html',
        publications=publications,
        form=form
    )


@pub.route('/profesor/<user>/')
def list(user):
    form = AddPublicationForm()
    publications = Publication.select().where(Publication.owner == user)
    return render_template(
        'publications/list.html',
        publications=publications,
        form=form
    )


@pub.route('/doi/<path:doi>/')
def view(doi):
    try:
        publication = Publication.get(Publication.doi == doi)
    except:
        abort(404)
    else:
        return render_template(
            'publications/view.html',
            publication=publication
        )


@pub.route('/add/', methods=['POST'])
@flask_login.login_required
def add():
    user = flask_login.current_user
    form = AddPublicationForm()
    if form.validate_on_submit():
        f = form.proofs.data
        filename = secure_filename(user.id + f.filename)
        f.save(os.path.join(
            app.instance_path, 'files', 'publications', filename
        ))
        # TODO: revisar que el doi pertenezca a una revista
        Publication.create(
            doi=form.doi.data,
            proofs_file=filename,
            owner=user.id,
            journal=Journal.get(Journal.issn == form.issn.data)
        )
        return redirect(url_for('publications.list', user=user.id))
    else:
        raise CurpudError(get_first_error(form))


@pub.route('/delete/', methods=['POST'])
@flask_login.login_required
def delete():
    raise CurpudError("Acción no implementada!")
    user = flask_login.current_user
    return redirect(url_for('publications.list', user=user.id))


@pub.route('/file/<path:doi>')
def serve_file(doi):
    try:
        publication = Publication.get(Publication.doi == doi)
    except:
        abort(404)
    else:
        return send_from_directory(
            os.path.join(app.instance_path, 'files', 'publications'),
            publication.proofs_file
        )

curpud/templates/example.html
{% extends "layout.html" %}


{% block title %}Sobre escribir título{% endblock %}


{% block body %}
<h1>Título de algo</h1>
{% endblock %}


{% block modals %}
{% endblock %}


{% block scripts %}
{% endblock %}

curpud/templates/layout.html
{% import "macros.html" as macros %}
{% from "macros.html" import navbar with context %}
{% set isnpjax = "X-PJAX" not in request.headers %}
{% if isnpjax %}
<!DOCTYPE html>
<html lang="es">
  <head>
{% endif %}
    {% block head %}
{% if isnpjax %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
{% endif %}

    <title>{% block title %}Hola Mundo{% endblock %} - curpud</title>

{% if isnpjax %}
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}" type="text/css"/>
{% endif %}
    {% endblock %}
{% if isnpjax %}
  </head>

  <body>

    <!-- Alerts container -->
    <div id='container-alert' class="alert-fixed"></div>

    <!-- Loader -->
    <div class="loader-container modal" hidden="hidden">
      <div class="loader"></div>
    </div>

    {{ navbar() }}
    <div class="container">
{% endif %}
      {% block main_container %}
{% if isnpjax %}
      <div class="row">
        <div class="container col-sm-3">
          {% block sidebar %}
          <nav>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="{{ url_for('publications.index') }}">Publicaciones</a></li>
              {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('publications.list', user=current_user.id) }}">Mis Publicaciones</a></li>
              {% endif %}
              <li><a href="{{ url_for('courses.index') }}">Cursos</a></li>
              {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('courses.list', user=current_user.id) }}">Mis Cursos</a></li>
              {% endif %}
              {% if current_user.is_authenticated and current_user.is_admin %}
              <li class="bg-danger"><a class="text-danger" href="{{ url_for('journal.index_view') }}">Zona de Administración</a></li>
              {% endif %}
              <li class="hidden-xs">
                <hr>
                <footer>
                  <small class="text-muted">
                    Copyright (c) 2016 - <a href="http://www.github.com/trivialbox">trivialbox</a>.
                  </small>
                </footer>
              </li>
            </ul>
          </nav>
          {% endblock %}
        </div>
        <div class="col-sm-9" id="main-content">
{% endif %}
          {% block body %}
          <h1>Hello, world!</h1>
          {% endblock %}
{% if isnpjax %}
        </div>
      </div>
{% endif %}
      {% endblock %}
{% if isnpjax %}
    </div>

{% endif %}

    {% block modals %}
    {% endblock %}

{% if isnpjax%}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='bower_components/jquery-pjax/jquery.pjax.js') }}"></script>
    <script src="{{ url_for('static', filename='js/common.js') }}"></script>
{% endif %}
    {% block scripts %}
    {% endblock %}
{% if isnpjax %}
  </body>
</html>
{% endif %}

curpud/templates/macros.html
{% macro make_form(form, id, submit="Agregar", excludes=['csrf_token'], form_extras=None, url=None) %}
<form id="{{ id }}" {{ form_extras }} action="{{ url }}">
  {{ form.hidden_tag() }}
  {% for field in form if field.name not in excludes %}
  <div class="form-group">
    {% set required = True if field.flags.required else False %}
    {% set form_class = "form-control-file" if field.type == 'FileField' else "form-control" %}
    {{ field.label }} {{ field(class=form_class, required=required) }}
  </div>
  {% endfor %}
  <button type="submit" class="btn btn-primary">{{ submit }}</button>
</form>
{% endmacro %}


{% macro make_modal_from_form(title, id, form, form_id, submit="Agregar", excludes=['csrf_token']) %}
<div id="{{ id }}" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">{{ title }}</h4>
      </div>
      <form id="{{ form_id }}">
        <div class="modal-body">
          {% for field in form if field.name not in excludes %}
          <div class="form-group">
            {% set required = True if field.flags.required else False %}
            {{ field.label }} {{ field(class="form-control", required=required) }}
          </div>
          {% endfor %}
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">{{ submit }}</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endmacro %}


{% macro make_confirm_modal(title, id, form_id, body, accept="Aceptar", cancel="Cancelar", action_type="danger") %}
<div id="{{ id }}" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">{{ title }}</h4>
      </div>
      <form id="{{ form_id }}">
        {% if body %}
        <div class="modal-body">
          {{ body }}
        </div>
        {% endif %}
        <div class="modal-footer">
          <button type="submit" class="btn btn-{{ action_type }}">
            {{ accept }}
          </button>
          <button type="button" class="btn btn-default" data-dismiss="modal">
            {{ cancel }}
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endmacro %}


{% macro js_send_request(form_id, url, message, type="POST", modal_id=None) %}
<script>
  sendRequest('#{{ form_id }}', '{{ type }}', '{{ url }}', function (data, status) {
    {% if message %}
    showAlert('alert-success', '{{ message }}');
    {% endif %}

    {% if modal_id %}
    modal = $('#{{ modal_id }}');
    modal.on('hidden.bs.modal', function (e) {
      $.pjax.reload('#main-content');
    });
    modal.modal('hide');
    {% else %}
    $.pjax.reload('#main-content');
    {% endif %}
  });
</script>
{% endmacro %}


{% macro navbar() %}
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">CURPUD</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              {{ current_user.name }}
              <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{ url_for('auth.logout') }}">Salir</a></li>
          </ul>
        </li>
        {% else %}
        <li>
          <a href="{{ url_for('auth.login') }}">Entrar</a>
        </li>
        {% endif %}
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</nav>
{% endmacro %}